import { Migration, Schema, Blueprint } from '@gravito/atlas'

/**
 * Create Sessions Table Migration
 * 
 * Generated by @gravito/fortify
 * For session-based authentication
 */
export default class CreateSessionsTable extends Migration {
    /**
     * Run the migration
     */
    async up(): Promise<void> {
        await Schema.create('sessions', (table: Blueprint) => {
            table.string('id').primary()
            table.foreignId('user_id').nullable().index()
            table.string('ip_address', 45).nullable()
            table.text('user_agent').nullable()
            table.text('payload')
            table.integer('last_activity').index()
        })
    }

    /**
     * Reverse the migration
     */
    async down(): Promise<void> {
        await Schema.dropIfExists('sessions')
    }
}
