import fs from 'node:fs/promises'
import path from 'node:path'
import { Painter as pc } from '@gravito/chromatic'
import { z } from 'zod'
import { CliError } from '../errors/CliError'
import { CliErrorCodes } from '../errors/codes'

type JsonSchemaObject = Record<string, unknown> & {
  properties?: Record<string, { type?: string; [key: string]: unknown }>
  required?: string[]
}

type OpenApiParameter = {
  name: string
  in: 'path' | 'query'
  required: boolean
  schema: Record<string, unknown>
}

type OpenApiOperation = {
  operationId: string
  responses: Record<
    string,
    {
      description: string
      content?: Record<string, { schema: Record<string, unknown> }>
    }
  >
  requestBody?: {
    content: Record<string, { schema: Record<string, unknown> }>
  }
  parameters?: OpenApiParameter[]
}

type OpenApiSpec = {
  openapi: string
  info: {
    title: string
    version: string
    description: string
  }
  paths: Record<string, Record<string, OpenApiOperation>>
  components: {
    schemas: Record<string, unknown>
  }
}

/**
 * Convert Zod schema to JSON Schema for OpenAPI 3.1 embedding.
 * Uses Zod v4 native z.toJSONSchema() — no external dependency.
 * Returns {} for null/undefined/non-Zod inputs (e.g., z.any(), z.unknown()).
 * Throws on conversion failure per D-07.
 */
function convertToOpenApi(schema: unknown): JsonSchemaObject {
  if (!schema || typeof schema !== 'object' || !('_def' in schema)) {
    return {}
  }

  try {
    const result = z.toJSONSchema(schema as z.ZodType) as JsonSchemaObject
    const { $schema, ...rest } = result
    return rest
  } catch (err) {
    throw new Error(
      `Zod schema conversion failed: ${err instanceof Error ? err.message : String(err)}`
    )
  }
}

/**
 * Generate OpenAPI 3.1 specification from registered routes.
 *
 * @param options - Generation options.
 * @param options.entry - The entry file of the application.
 * @param options.output - The output path for openapi.json.
 * @public
 */
export async function openapiGenerate(options: {
  entry: string
  output: string
  title?: string
  version?: string
}) {
  try {
    const cwd = process.cwd()
    const entryPath = path.resolve(cwd, options.entry)
    const outputPath = path.resolve(cwd, options.output)

    console.log(pc.cyan(`\n🔍 Scanning for routes in ${options.entry}...`))

    // Import the app
    const module = await import(entryPath)
    const mod = typeof module === 'object' && module !== null ? module : {}
    const defaultExport =
      typeof mod.default === 'object' && mod.default !== null ? mod.default : undefined

    // Try to find PlanetCore instance
    const core = mod.core || defaultExport?.core || mod.app?.core || defaultExport?.app?.core

    if (!core || !core.router || typeof core.router.compile !== 'function') {
      throw new CliError(500, CliErrorCodes.APP_INSTANCE_NOT_FOUND, {
        message:
          'Could not find a valid Gravito PlanetCore instance with a router in the entry file.',
      })
    }

    const compiledRoutes = core.router.compile()

    const spec: OpenApiSpec = {
      openapi: '3.1.0',
      info: {
        title: options.title || 'Gravito API',
        version: options.version || '1.0.0',
        description: 'Automatically generated by Gravito CLI',
      },
      paths: {},
      components: {
        schemas: {},
      },
    }

    let routeCount = 0
    let schemaCount = 0

    for (const route of compiledRoutes) {
      const { method, path: routePath, name, schema } = route
      const lowerMethod = method.toLowerCase()

      // Convert path params :id to {id}
      const openApiPath = routePath.replace(/:([A-Za-z0-9_]+)/g, '{$1}')

      if (!spec.paths[openApiPath]) {
        spec.paths[openApiPath] = {}
      }

      const operation: OpenApiOperation = {
        operationId: name || `${lowerMethod}${openApiPath.replace(/[^a-zA-Z0-9]/g, '_')}`,
        responses: {
          '200': {
            description: 'Successful response',
          },
        },
      }

      if (schema) {
        schemaCount++

        // 1. Request Body
        if (schema.body) {
          try {
            operation.requestBody = {
              content: {
                'application/json': {
                  schema: convertToOpenApi(schema.body),
                },
              },
            }
          } catch (err) {
            throw new CliError(500, CliErrorCodes.SCHEMA_CONVERSION_FAILED, {
              message: `Route ${method} ${routePath}: body schema conversion failed - ${
                err instanceof Error ? err.message : String(err)
              }`,
            })
          }
        }

        // 2. Path Parameters & Query
        const parameters: OpenApiParameter[] = []

        if (schema.params) {
          try {
            const paramsSchema = convertToOpenApi(schema.params)
            if (paramsSchema.properties) {
              for (const [key, prop] of Object.entries(paramsSchema.properties)) {
                parameters.push({
                  name: key,
                  in: 'path',
                  required: true,
                  schema: prop,
                })
              }
            }
          } catch (err) {
            throw new CliError(500, CliErrorCodes.SCHEMA_CONVERSION_FAILED, {
              message: `Route ${method} ${routePath}: params schema conversion failed - ${
                err instanceof Error ? err.message : String(err)
              }`,
            })
          }
        }

        if (schema.query) {
          try {
            const querySchema = convertToOpenApi(schema.query)
            if (querySchema.properties) {
              for (const [key, prop] of Object.entries(querySchema.properties)) {
                parameters.push({
                  name: key,
                  in: 'query',
                  required: querySchema.required?.includes(key) || false,
                  schema: prop,
                })
              }
            }
          } catch (err) {
            throw new CliError(500, CliErrorCodes.SCHEMA_CONVERSION_FAILED, {
              message: `Route ${method} ${routePath}: query schema conversion failed - ${
                err instanceof Error ? err.message : String(err)
              }`,
            })
          }
        }

        if (parameters.length > 0) {
          operation.parameters = parameters
        }

        // 3. Response
        if (schema.response) {
          try {
            operation.responses['200'] = {
              description: 'Successful response',
              content: {
                'application/json': {
                  schema: convertToOpenApi(schema.response),
                },
              },
            }
          } catch (err) {
            throw new CliError(500, CliErrorCodes.SCHEMA_CONVERSION_FAILED, {
              message: `Route ${method} ${routePath}: response schema conversion failed - ${
                err instanceof Error ? err.message : String(err)
              }`,
            })
          }
        }
      }

      spec.paths[openApiPath][lowerMethod] = operation
      routeCount++
    }

    // Ensure directory exists
    await fs.mkdir(path.dirname(outputPath), { recursive: true })

    // Write spec
    await fs.writeFile(outputPath, JSON.stringify(spec, null, 2))

    console.log(pc.green(`\n✨ Successfully generated OpenAPI specification!`))
    console.log(`${pc.bold('Routes processed:')} ${routeCount}`)
    console.log(`${pc.bold('Schemas extracted:')} ${schemaCount}`)
    console.log(`${pc.bold('Output file:')} ${options.output}\n`)
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err)
    console.error(pc.red(`Failed to generate OpenAPI spec: ${message}`))
    process.exit(1)
  }
}
