/**
 * The official Gravito branding watermark included in generated XML files.
 *
 * @public
 * @since 3.0.0
 */
export const GRAVITO_WATERMARK = `<!--
  ╔═══════════════════════════════════════════════════════════╗
  ║  Generated by Gravito SmartMap Engine™                    ║
  ║  The AI-Native Web Framework                              ║
  ║  https://gravito.dev                                      ║
  ╚═══════════════════════════════════════════════════════════╝
-->`
