import { file, spawn, write } from 'bun'

const isDtsOnly = process.argv.includes('--dts-only')

console.log('🔨 Building @gravito/luminosity-cli in parallel...')

// Clean dist
await Bun.$`rm -rf dist`

// Build main entry and CLI binary in parallel (independent builds)
async function buildInParallel() {
  // Task 1: Build main entry (src/index.ts → dist/)
  const tsupMainPromise = (async () => {
    const tsupMain = spawn(
      [
        'bunx',
        'tsup',
        'src/index.ts',
        '--format',
        isDtsOnly ? 'esm' : 'esm,cjs',
        ...(isDtsOnly ? ['--dts', '--dts-only'] : []),
        '--tsconfig',
        'tsconfig.build.json',
        '--external',
        '@gravito/luminosity,commander,picocolors',
        '--outDir',
        'dist',
      ],
      {
        stdout: 'inherit',
        stderr: 'inherit',
      }
    )

    const code = await tsupMain.exited
    if (code !== 0) {
      console.error('❌ tsup main build failed')
      return 1
    }
    return 0
  })()

  // Task 2: Build CLI binary (bin/gravito-seo.ts → dist/bin/)
  const tsupCliPromise = (async () => {
    const tsupCli = spawn(
      [
        'bunx',
        'tsup',
        'bin/gravito-seo.ts',
        '--format',
        'esm',
        '--tsconfig',
        'tsconfig.build.json',
        '--external',
        '@gravito/luminosity,commander,picocolors',
        '--outDir',
        'dist/bin',
        '--no-dts', // types already generated by main build
      ],
      {
        stdout: 'inherit',
        stderr: 'inherit',
      }
    )

    const code = await tsupCli.exited
    if (code !== 0) {
      console.error('❌ tsup CLI build failed')
      return 1
    }
    return 0
  })()

  // Wait for both builds
  const [mainCode, cliCode] = await Promise.all([tsupMainPromise, tsupCliPromise])

  if (mainCode !== 0 || cliCode !== 0) {
    process.exit(1)
  }
}

// Execute parallel build
await buildInParallel()

// Add shebang to CLI binary and make executable
const cliFile = './dist/bin/gravito-seo.js'
const content = await file(cliFile).text()
const withShebang = content.startsWith('#!/usr/bin/env node')
  ? content
  : `#!/usr/bin/env node\n${content}`
await write(cliFile, withShebang)
await Bun.spawn(['chmod', '+x', cliFile]).exited

console.log('✅ Build completed')
process.exit(0)
