import { execSync } from 'child_process'

console.log('Building @gravito/atlas...')

// Clean dist
await Bun.$`rm -rf dist`

try {
  // Build ESM and CJS bundles - no DTS to avoid memory issues
  // DTS will be generated by the consumer's TypeScript
  execSync(
    'npx tsup src/index.ts --format esm,cjs --external pg,mysql2,better-sqlite3,mongodb,ioredis --outDir dist --target esnext',
    {
      stdio: 'inherit',
      env: process.env,
    }
  )

  // Generate a minimal typings file as fallback
  console.log('Generating minimal type stub...')
  await Bun.$`echo "export * from './src/index';" > dist/index.d.ts`

  console.log('✅ Build complete!')
} catch (_error) {
  console.error('❌ Build failed')
  process.exit(1)
}
