/**
 * Tests: TypeGenerator
 * @description Unit tests for TypeGenerator (model scanning) and TypeWriter (declaration output).
 */

import { describe, expect, it } from 'bun:test'
import type { ModelTypeMap } from '../src/schema/TypeGenerator'
import { TypeWriter } from '../src/schema/TypeWriter'

// ============================================================================
// TypeWriter Tests (pure unit – no FS I/O)
// ============================================================================

describe('TypeWriter', () => {
  describe('buildContent()', () => {
    it('generates correct interface declaration for a simple model', () => {
      const maps: ModelTypeMap[] = [
        {
          modelName: 'User',
          tableName: 'users',
          columns: {
            id: 'number',
            name: 'string',
            email: 'string',
          },
        },
      ]

      const writer = new TypeWriter({ outputPath: '/tmp/test.d.ts' })
      const content = writer.buildContent(maps)

      expect(content).toContain('export interface GeneratedUser')
      expect(content).toContain('id: number')
      expect(content).toContain('name: string')
      expect(content).toContain('email: string')
    })

    it('marks nullable columns with optional modifier', () => {
      const maps: ModelTypeMap[] = [
        {
          modelName: 'Post',
          tableName: 'posts',
          columns: {
            id: 'number',
            body: 'string | null',
            published_at: 'Date | string | null',
          },
        },
      ]

      const writer = new TypeWriter({ outputPath: '/tmp/test.d.ts' })
      const content = writer.buildContent(maps)

      expect(content).toContain('body?: string | null')
      expect(content).toContain('published_at?: Date | string | null')
      // Non-nullable id should NOT have ?
      expect(content).toContain('id: number')
      expect(content).not.toContain('id?: number')
    })

    it('generates multiple interfaces for multiple models', () => {
      const maps: ModelTypeMap[] = [
        { modelName: 'User', tableName: 'users', columns: { id: 'number' } },
        { modelName: 'Comment', tableName: 'comments', columns: { id: 'number', text: 'string' } },
      ]

      const writer = new TypeWriter({ outputPath: '/tmp/test.d.ts' })
      const content = writer.buildContent(maps)

      expect(content).toContain('export interface GeneratedUser')
      expect(content).toContain('export interface GeneratedComment')
      expect(content).toContain('text: string')
    })

    it('includes auto-generated banner comment', () => {
      const writer = new TypeWriter({ outputPath: '/tmp/test.d.ts' })
      const content = writer.buildContent([])

      expect(content).toContain('DO NOT EDIT THIS FILE MANUALLY')
      expect(content).toContain('bun orbit generate:types')
    })

    it('includes custom banner when provided', () => {
      const writer = new TypeWriter({
        outputPath: '/tmp/test.d.ts',
        banner: '// Custom banner',
      })
      const content = writer.buildContent([])
      expect(content).toContain('// Custom banner')
    })

    it('returns empty interfaces for model with no columns', () => {
      const maps: ModelTypeMap[] = [{ modelName: 'Empty', tableName: 'empty', columns: {} }]
      const writer = new TypeWriter({ outputPath: '/tmp/test.d.ts' })
      const content = writer.buildContent(maps)

      expect(content).toContain('export interface GeneratedEmpty {')
      expect(content).toContain('}')
    })

    it('includes table name in the doc comment', () => {
      const maps: ModelTypeMap[] = [
        { modelName: 'Product', tableName: 'products_catalog', columns: { id: 'number' } },
      ]
      const writer = new TypeWriter({ outputPath: '/tmp/test.d.ts' })
      const content = writer.buildContent(maps)

      expect(content).toContain('table: products_catalog')
    })
  })
})
