/**
 * Represents the entity that sent a message.
 *
 * - CUSTOMER: The end-user seeking support.
 * - SUPPORT: The support agent responding to the customer.
 * - SYSTEM: Automated messages generated by the platform.
 */
export type MessageSender = 'CUSTOMER' | 'SUPPORT' | 'SYSTEM'

/**
 * Categorizes the nature of a conversation.
 *
 * - ORDER: Inquiries related to specific orders.
 * - PRODUCT: Questions about product details or availability.
 * - GENERAL: Non-specific or miscellaneous inquiries.
 */
export type ConversationType = 'ORDER' | 'PRODUCT' | 'GENERAL'

/**
 * Represents the current state of the WebSocket connection.
 */
export type ConnectionStatus = 'connecting' | 'connected' | 'disconnected' | 'error'

/**
 * Tracks the delivery lifecycle of a message.
 *
 * - sending: Message is being transmitted to the server.
 * - sent: Message has been received by the server.
 * - delivered: Message has been successfully delivered to the recipient.
 * - failed: Message could not be sent.
 */
export type MessageStatus = 'sending' | 'sent' | 'delivered' | 'failed'

/**
 * Represents the lifecycle state of a conversation.
 *
 * - ACTIVE: The conversation is currently ongoing.
 * - PENDING: The conversation is waiting for an agent to join or respond.
 * - CLOSED: The conversation has been concluded.
 */
export type ConversationStatus = 'ACTIVE' | 'PENDING' | 'CLOSED'

/**
 * Represents a single message within a chat session.
 */
export interface ChatMessage {
  /** Unique identifier for the message. */
  readonly id: string
  /** Identifier of the conversation this message belongs to. */
  readonly conversationId: string
  /** The entity that authored the message. */
  readonly sender: MessageSender
  /** The textual content of the message. */
  readonly content: string
  /** Current delivery status of the message. */
  readonly status: MessageStatus
  /** Timestamp when the message was created. */
  readonly createdAt: Date
  /** Additional structured data associated with the message. */
  readonly metadata?: Readonly<Record<string, unknown>>
}

/**
 * A specialized message generated by the system.
 */
export interface SystemMessage extends Omit<ChatMessage, 'sender'> {
  /** Always set to 'SYSTEM' for system-generated messages. */
  readonly sender: 'SYSTEM'
  /** The specific type of system event. */
  readonly type: 'WELCOME' | 'AGENT_JOINED' | 'AGENT_LEFT' | 'SESSION_ENDED'
}

/**
 * Provides business context for a conversation, such as an associated order or product.
 */
export interface ConversationContext {
  /** The category of the context. */
  readonly type: ConversationType
  /** The unique identifier of the related business entity (e.g., Order ID). */
  readonly id?: string
  /** A human-readable title for the context. */
  readonly title?: string
  /** Additional structured data for the context. */
  readonly metadata?: Readonly<Record<string, unknown>>
}

/**
 * Represents a complete support chat session.
 */
export interface Conversation {
  /** Unique identifier for the conversation. */
  readonly id: string
  /** Identifier of the customer, if authenticated. */
  readonly customerId?: string
  /** Business context associated with this conversation. */
  readonly context?: ConversationContext
  /** Current lifecycle status of the conversation. */
  readonly status: ConversationStatus
  /** Timestamp when the conversation was initiated. */
  readonly createdAt: Date
  /** Timestamp of the last activity in the conversation. */
  readonly updatedAt: Date
}

/**
 * Options for paginating through message history.
 */
export interface PaginationOptions {
  /** Maximum number of messages to retrieve per request. */
  readonly limit?: number
  /** Cursor for fetching the next or previous set of results. */
  readonly cursor?: string
  /** The direction of pagination relative to the cursor. */
  readonly direction?: 'before' | 'after'
}

/**
 * Response structure for message list requests.
 */
export interface MessagesResponse {
  /** The list of retrieved messages. */
  readonly messages: readonly ChatMessage[]
  /** Indicates if more messages are available for retrieval. */
  readonly hasMore: boolean
  /** Cursor to use for fetching the next page of messages. */
  readonly nextCursor?: string
}

/**
 * Standardized error codes for API operations.
 */
export type ApiErrorCode =
  | 'NETWORK_ERROR'
  | 'AUTH_ERROR'
  | 'NOT_FOUND'
  | 'RATE_LIMITED'
  | 'SERVER_ERROR'
  | 'VALIDATION_ERROR'

/**
 * Represents an error returned by the Support API.
 */
export interface ApiError {
  /** Machine-readable error code. */
  readonly code: ApiErrorCode
  /** Human-readable error description. */
  readonly message: string
  /** Indicates if the operation can be safely retried. */
  readonly retryable: boolean
}

/**
 * Generic wrapper for API responses.
 *
 * @template T - The type of the data payload.
 */
export interface ApiResponse<T> {
  /** Indicates if the request was successful. */
  readonly success: boolean
  /** The response payload, present on success. */
  readonly data?: T
  /** Error details, present on failure. */
  readonly error?: ApiError
}

/**
 * Configuration properties for the Support Chat Widget component.
 *
 * @example
 * ```tsx
 * <SupportChatWidget
 *   apiBaseUrl="https://api.gravito.io"
 *   wsUrl="wss://ws.gravito.io"
 *   context={{
 *     type: 'ORDER',
 *     id: 'ORD-12345',
 *     title: 'Order Inquiry'
 *   }}
 * />
 * ```
 */
export interface ChatWidgetProps {
  /**
   * Base URL for the Gravito Support API.
   * @example "https://api.gravito.io"
   */
  readonly apiBaseUrl: string

  /**
   * URL for the real-time WebSocket connection.
   * @example "wss://ws.gravito.io"
   */
  readonly wsUrl: string

  /**
   * Optional business context to associate with the conversation.
   */
  readonly context?: ConversationContext

  /**
   * Optional CSS class name for custom styling.
   */
  readonly className?: string

  /**
   * Whether the chat widget should be open by default.
   * @default false
   */
  readonly defaultOpen?: boolean

  /**
   * Callback triggered when the widget's open state changes.
   */
  readonly onOpenChange?: (open: boolean) => void

  /**
   * Callback triggered when the WebSocket connection status changes.
   */
  readonly onConnectionChange?: (status: ConnectionStatus) => void
}

/**
 * Configuration for the WebSocket hook.
 */
export interface UseWebSocketOptions {
  /** WebSocket connection URL. */
  readonly wsUrl: string
  /** Identifier of the active conversation. */
  readonly conversationId: string | null
  /** Callback triggered when a new message is received. */
  readonly onMessage: (message: ChatMessage) => void
  /** Callback triggered when the connection status changes. */
  readonly onStatusChange?: (status: ConnectionStatus) => void
}

/**
 * Return type for the WebSocket hook.
 */
export interface UseWebSocketReturn {
  /** Current connection status. */
  readonly status: ConnectionStatus
  /** Establishes the WebSocket connection. */
  readonly connect: () => Promise<void>
  /** Terminates the WebSocket connection. */
  readonly disconnect: () => void
  /** Emits a custom event to the server. */
  readonly emit: (event: string, data: unknown) => void
  /** Subscribes to a custom event from the server. Returns an unsubscribe function. */
  readonly on: (event: string, callback: (data: unknown) => void) => () => void
}

/**
 * Configuration for the typing status hook.
 */
export interface UseTypingStatusOptions {
  /** Identifier of the active conversation. */
  readonly conversationId: string | null
  /** Callback triggered when the typing status of the other party changes. */
  readonly onTypingChange?: (isTyping: boolean) => void
  /** Method to emit typing events. */
  readonly emit?: (event: string, data: unknown) => void
  /** Method to subscribe to typing events. */
  readonly on?: (event: string, callback: (data: unknown) => void) => () => void
}

/**
 * Configuration for the messages hook.
 */
export interface UseMessagesOptions {
  /** Base URL for the Support API. */
  readonly apiBaseUrl: string
  /** Identifier of the active conversation. */
  readonly conversationId: string | null
}

/**
 * Return type for the messages hook.
 */
export interface UseMessagesReturn {
  /** List of messages in the current conversation. */
  readonly messages: readonly ChatMessage[]
  /** Indicates if messages are currently being loaded. */
  readonly isLoading: boolean
  /** Error encountered during message operations, if any. */
  readonly error: Error | null
  /** Sends a new message to the conversation. */
  readonly sendMessage: (content: string) => Promise<void>
  /** Fetches the next page of message history. */
  readonly loadMore: () => Promise<void>
  /** Indicates if more historical messages are available. */
  readonly hasMore: boolean
}

/**
 * Configuration for the conversation hook.
 */
export interface UseConversationOptions {
  /** Base URL for the Support API. */
  readonly apiBaseUrl: string
  /** Initial context for the conversation. */
  readonly context?: ConversationContext
  /** Key used for persisting conversation state in local storage. */
  readonly storageKey?: string
}

/**
 * Return type for the conversation hook.
 */
export interface UseConversationReturn {
  /** The current conversation object. */
  readonly conversation: Conversation | null
  /** Unique identifier of the current conversation. */
  readonly conversationId: string | null
  /** Indicates if the conversation is being initialized. */
  readonly isInitializing: boolean
  /** Error encountered during conversation operations, if any. */
  readonly error: Error | null
  /** Initiates a new conversation session. */
  readonly createConversation: () => Promise<void>
  /** Concludes the current conversation session. */
  readonly endConversation: () => Promise<void>
}

/**
 * Return type for the error handler hook.
 */
export interface UseErrorHandlerReturn {
  /** The current error object. */
  readonly error: Error | null
  /** Processes an error and optionally provides a retry mechanism. */
  readonly handleError: (error: Error, retry?: () => void) => void
  /** Clears the current error state. */
  readonly clearError: () => void
  /** Executes the retry logic for the last error. */
  readonly retry: () => void
}

/**
 * Configuration for the main Chat Widget hook.
 */
export interface UseChatWidgetOptions extends ChatWidgetProps {}

/**
 * Return type for the main Chat Widget hook, providing state and actions for the UI.
 */
export interface UseChatWidgetReturn {
  /** Whether the chat window is currently visible. */
  readonly isOpen: boolean
  /** List of messages in the current conversation. */
  readonly messages: readonly ChatMessage[]
  /** Current WebSocket connection status. */
  readonly connectionStatus: ConnectionStatus
  /** Indicates if the widget is performing an initial load or operation. */
  readonly isLoading: boolean
  /** Current error state, if any. */
  readonly error: Error | null
  /** The active conversation session. */
  readonly conversation: Conversation | null
  /** Indicates if a support agent is currently typing. */
  readonly isTyping: boolean
  /** Indicates if more historical messages can be loaded. */
  readonly hasMore: boolean

  /** Opens the chat window. */
  readonly open: () => void
  /** Closes the chat window. */
  readonly close: () => void
  /** Toggles the visibility of the chat window. */
  readonly toggle: () => void
  /** Sends a message in the current conversation. */
  readonly sendMessage: (content: string) => Promise<void>
  /** Loads more historical messages. */
  readonly loadMore: () => Promise<void>
  /** Retries the last failed operation. */
  readonly retry: () => void
  /** Clears the current error state. */
  readonly clearError: () => void
  /** Concludes the current conversation. */
  readonly endConversation: () => Promise<void>
}

/**
 * Properties for the ChatHeader component.
 */
export interface ChatHeaderProps {
  /** Callback triggered when the close button is clicked. */
  readonly onClose: () => void
  /** Current connection status to display. */
  readonly connectionStatus: ConnectionStatus
  /** Name of the support agent, if assigned. */
  readonly agentName?: string
  /** URL of the support agent's avatar image. */
  readonly agentAvatar?: string
}

/**
 * Properties for the ChatMessages component.
 */
export interface ChatMessagesProps {
  /** List of messages to display. */
  readonly messages: readonly ChatMessage[]
  /** Indicates if messages are currently being loaded. */
  readonly isLoading: boolean
  /** Callback triggered when the user scrolls to load more messages. */
  readonly onLoadMore?: () => void
  /** Indicates if more historical messages are available. */
  readonly hasMore: boolean
}

/**
 * Properties for an individual ChatMessage component.
 */
export interface ChatMessageProps {
  /** The message data to render. */
  readonly message: ChatMessage
  /** Callback to retry sending the message if it failed. */
  readonly onRetry?: () => void
}

/**
 * Properties for the ChatInput component.
 */
export interface ChatInputProps {
  /** Callback triggered when a message is submitted. */
  readonly onSend: (content: string) => void
  /** Whether the input is currently disabled. */
  readonly disabled?: boolean
  /** Placeholder text for the input field. */
  readonly placeholder?: string
  /** Maximum allowed length for a message. */
  readonly maxLength?: number
}

/**
 * Properties for the ChatTrigger component (the button that opens the chat).
 */
export interface ChatTriggerProps {
  /** Callback triggered when the trigger is clicked. */
  readonly onClick: () => void
  /** Indicates if there are unread messages. */
  readonly hasUnread: boolean
  /** Whether the chat window is currently open. */
  readonly isOpen: boolean
}

/**
 * Properties for the ContextBanner component, which shows related business info.
 */
export interface ContextBannerProps {
  /** The business context to display. */
  readonly context: ConversationContext
  /** Callback triggered when the banner is dismissed. */
  readonly onDismiss?: () => void
}

/**
 * Properties for the ConnectionStatus indicator component.
 */
export interface ConnectionStatusProps {
  /** The connection status to represent. */
  readonly status: ConnectionStatus
  /** Callback to manually trigger a reconnection attempt. */
  readonly onRetry?: () => void
}

/**
 * Properties for the TypingIndicator component.
 */
export interface TypingIndicatorProps {
  /** Whether to show the typing animation. */
  readonly isTyping: boolean
  /** Name of the agent who is typing. */
  readonly agentName?: string
}

/**
 * Properties for the ErrorBoundary component.
 */
export interface ErrorBoundaryProps {
  /** The components to be wrapped by the error boundary. */
  readonly children: React.ReactNode
  /** Custom UI to display when an error occurs. */
  readonly fallback?: React.ReactNode
  /** Callback triggered when an error is caught. */
  readonly onError?: (error: Error, errorInfo: React.ErrorInfo) => void
}

/**
 * Options for configuring state persistence.
 */
export interface StorageOptions {
  /** Whether to encrypt the stored data. */
  readonly encrypt?: boolean
  /** Time-to-live for the stored data in milliseconds. */
  readonly expiry?: number
}

/**
 * Represents the structure of the persisted chat state.
 */
export interface PersistedState {
  /** Identifier of the persisted conversation. */
  readonly conversationId: string | null
  /** Cache of recent messages. */
  readonly messages: readonly ChatMessage[]
  /** Messages that are queued for sending. */
  readonly pendingMessages: readonly ChatMessage[]
  /** Timestamp of the last synchronization with the server. */
  readonly lastSyncAt: number
  /** Persisted business context. */
  readonly context?: ConversationContext
}

/**
 * Represents the result of a validation operation.
 */
export interface ValidationResult {
  /** Indicates if the validation was successful. */
  readonly success: boolean
  /** The validated data, present on success. */
  readonly data?: string
  /** Error message, present on failure. */
  readonly error?: string
}
