/**
 * @gravito/atlas - Type Writer
 * @description Writes TypeScript declaration files from generated Model type maps.
 *
 * Outputs interface declarations that can be merged into Model classes via
 * Declaration Merging for zero type-drift DX.
 */

import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import type { ModelTypeMap } from './TypeGenerator'

export interface TypeWriterOptions {
  /** Output file path (e.g., '.orbit/generated.d.ts') */
  outputPath: string
  /** Optional banner comment */
  banner?: string
}

/**
 * TypeWriter
 *
 * Converts a list of ModelTypeMap objects into a `.d.ts` declaration file.
 *
 * @example
 * ```typescript
 * const writer = new TypeWriter({ outputPath: '.orbit/generated.d.ts' })
 * await writer.write(typeMaps)
 * // Emits:
 * //   export interface GeneratedUser { id: number; name: string; ... }
 * ```
 */
export class TypeWriter {
  private readonly outputPath: string
  private readonly banner: string

  constructor(options: TypeWriterOptions) {
    this.outputPath = resolve(options.outputPath)
    this.banner =
      options.banner ??
      `/**
 * Atlas ORM - Auto-generated type definitions
 * DO NOT EDIT THIS FILE MANUALLY.
 * Run 'bun orbit generate:types' to regenerate.
 *
 * Generated at: ${new Date().toISOString()}
 */`
  }

  /**
   * Write the declaration file to disk.
   *
   * @param typeMaps - Array of model type maps from TypeGenerator
   */
  async write(typeMaps: ModelTypeMap[]): Promise<void> {
    const content = this.buildContent(typeMaps)

    // Ensure parent directory exists
    await mkdir(dirname(this.outputPath), { recursive: true })
    await writeFile(this.outputPath, content, 'utf8')
  }

  /**
   * Build the .d.ts file content string.
   */
  buildContent(typeMaps: ModelTypeMap[]): string {
    const lines: string[] = [this.banner, '']

    for (const map of typeMaps) {
      lines.push(`/**`)
      lines.push(` * Auto-generated types for ${map.modelName} model (table: ${map.tableName})`)
      lines.push(` */`)
      lines.push(`export interface Generated${map.modelName} {`)

      for (const [col, tsType] of Object.entries(map.columns)) {
        const isNullable = tsType.includes('| null')
        const optionalMark = isNullable ? '?' : ''
        const cleanType = isNullable ? `${tsType.replace(' | null', '')} | null` : tsType
        lines.push(`  ${col}${optionalMark}: ${cleanType}`)
      }

      lines.push(`}`)
      lines.push('')
    }

    return lines.join('\n')
  }
}
