import type { ContentfulStatusCode } from '@gravito/core'
import { AuthorizationException, ValidationException } from '@gravito/core'
import type { Context, MiddlewareHandler } from '@gravito/core/compat'
import type { z } from 'zod'
import { BlueprintGenerator } from './core/BlueprintGenerator'
// Import extracted components
import { DataExtractor, type DataSource } from './core/DataExtractor'
import { type SchemaValidationResult, SchemaValidatorFactory } from './validation/SchemaValidator'
// Initialize validators (this must happen for the factory to work)
import './validation/index'

/**
 * Detailed validation error information for a single field
 *
 * Used to represent the reason for validation failure for each field in a structured way, allowing the frontend to precisely display error messages next to the corresponding fields.
 * Uses dot notation paths (e.g., 'user.email') to represent the location of fields within nested objects.
 *
 * @public
 * @since 3.0.0
 *
 * @example
 * ```typescript
 * const error: ValidationErrorDetail = {
 *   field: 'user.email',
 *   message: 'Invalid email format',
 *   code: 'invalid_string'
 * }
 * ```
 */
export interface ValidationErrorDetail {
  /** Name of the field where the error occurred (uses dot notation for nested paths) */
  field: string
  /** Human-readable error message */
  message: string
  /** Machine-readable error code for programmatic handling (e.g., 'too_small') */
  code?: string | undefined
}

/**
 * Structured validation error response format
 *
 * Provides a unified API error response format, allowing the frontend to handle validation failures and authorization failures consistently.
 * Follows REST API best practices by structuring error information into a programmatically processable format.
 *
 * @public
 * @since 3.0.0
 *
 * @example
 * ```typescript
 * const response: ValidationErrorResponse = {
 *   success: false,
 *   error: {
 *     code: 'VALIDATION_ERROR',
 *     message: 'Validation failed',
 *     details: [
 *       { field: 'email', message: 'Invalid email format', code: 'invalid_string' }
 *     ]
 *   }
 * }
 * ```
 */
export interface ValidationErrorResponse {
  /** Always false for error responses, used for unified response format identification */
  success: false
  /** Error information container */
  error: {
    /** High-level error type code, used to distinguish between validation and authorization errors */
    code: 'VALIDATION_ERROR' | 'AUTHORIZATION_ERROR'
    /** General error message summary */
    message: string
    /** Array of detailed validation errors at the field level */
    details: ValidationErrorDetail[]
  }
}

/**
 * Internationalization Message Provider Interface
 *
 * Used to convert error codes generated by validators into localized, user-friendly messages.
 * Supports multi-language applications to display appropriate error messages based on user language preferences.
 *
 * @public
 * @since 3.0.0
 *
 * @example
 * ```typescript
 * class ChineseMessageProvider implements MessageProvider {
 *   getMessage(code: string, field: string, defaultMessage: string): string {
 *     const messages = {
 *       'email.invalid_string': 'Invalid email format',
 *       'name.too_small': 'Name must be at least 2 characters'
 *     }
 *     return messages[`${field}.${code}`] ?? defaultMessage
 *   }
 *
 *   getValidationFailedMessage(): string {
 *     return 'Validation failed'
 *   }
 *
 *   getUnauthorizedMessage(): string {
 *     return 'Unauthorized'
 *   }
 * }
 * ```
 */
export interface MessageProvider {
  /**
   * Get localized message based on error code and field name
   *
   * @param code - Error code generated by the validator
   * @param field - Field name
   * @param defaultMessage - Fallback message if no corresponding translation is found
   * @returns Localized error message
   */
  getMessage(code: string, field: string, defaultMessage: string): string
  /** Get a general "Validation failed" summary message */
  getValidationFailedMessage(): string
  /** Get a general "Unauthorized" summary message */
  getUnauthorizedMessage(): string
}

/**
 * Default Message Provider Implementation
 *
 * Does not perform any localization conversion and returns the validator's original English messages directly.
 * Suitable for applications that do not require internationalization support, or as a reference for custom implementations.
 *
 * @public
 * @since 3.0.0
 *
 * @example
 * ```typescript
 * const provider = new DefaultMessageProvider()
 * const message = provider.getMessage('invalid_string', 'email', 'Invalid email')
 * // Returns: 'Invalid email'
 * ```
 */
export class DefaultMessageProvider implements MessageProvider {
  getMessage(_code: string, _field: string, defaultMessage: string): string {
    return defaultMessage
  }
  getValidationFailedMessage(): string {
    return 'Validation failed'
  }
  getUnauthorizedMessage(): string {
    return 'Unauthorized'
  }
}

/**
 * Configuration options for FormRequest
 *
 * Allows customizing validation behavior, including HTTP status codes and error message localization.
 * These options enable you to adjust FormRequest to comply with your project's API design specifications.
 *
 * @public
 * @since 3.0.0
 *
 * @example
 * ```typescript
 * const options: FormRequestOptions = {
 *   errorStatus: 400,  // Use 400 instead of the default 422
 *   authErrorStatus: 401,  // Use 401 instead of the default 403
 *   messageProvider: new ChineseMessageProvider()  // Custom message provider
 * }
 * ```
 */
export interface FormRequestOptions {
  /** HTTP status code returned on validation error (Default: 422 Unprocessable Entity) */
  errorStatus?: ContentfulStatusCode
  /** HTTP status code returned on authorization failure (Default: 403 Forbidden) */
  authErrorStatus?: ContentfulStatusCode
  /** Custom internationalization message provider for localizing error messages */
  messageProvider?: MessageProvider
}

/**
 * FormRequest validation base class
 *
 * Provides a declarative request validation mechanism similar to Laravel FormRequest, separating validation logic from controllers.
 * Supports both Zod and Valibot, two mainstream TypeScript schema validation libraries, allowing you to choose your preferred tool.
 *
 * Core Design Philosophy:
 * - **Separation of Concerns**: Validation logic is independent of business logic, improving code maintainability.
 * - **Reusability**: The same FormRequest class can be reused across multiple routes.
 * - **Type Safety**: Leverages TypeScript's type inference to automatically assign the correct type to validated data.
 * - **Authorization Integration**: Allows checking user permissions before validation.
 *
 * @public
 * @since 3.0.0
 *
 * @example
 * ```typescript
 * // Using Zod
 * import { FormRequest } from '@gravito/impulse'
 * import { z } from 'zod'
 *
 * export class StoreUserRequest extends FormRequest {
 *   schema = z.object({
 *     name: z.string().min(2),
 *     email: z.string().email(),
 *   })
 *
 *   authorize(ctx: Context) {
 *     // Only administrators can create users
 *     return ctx.get('user')?.role === 'admin'
 *   }
 *
 *   messages() {
 *     return {
 *       'email.invalid_string': 'Please enter a valid email address',
 *       'name.too_small': 'Name must be at least 2 characters'
 *     }
 *   }
 * }
 *
 * // Using Valibot
 * import { FormRequest } from '@gravito/impulse'
 * import * as v from 'valibot'
 *
 * export class StoreUserRequest extends FormRequest {
 *   schema = v.object({
 *     name: v.pipe(v.string(), v.minLength(2)),
 *     email: v.pipe(v.string(), v.email()),
 *   })
 * }
 *
 * // Use in routes
 * app.post('/users', validateRequest(StoreUserRequest), async (ctx) => {
 *   const data = ctx.get('validated')  // Validated and type-safe data
 *   // ... business logic
 * })
 * ```
 */
export abstract class FormRequest<T = unknown> {
  /** Validation schema (Zod or Valibot), defining the structure and rules for request data */
  abstract schema: T

  /** Data Source: 'json' (request body), 'form' (form data), 'query' (query parameters), or 'param' (route parameters) */
  source: DataSource = 'json'

  /** Configuration options for customizing validation behavior and error handling */
  options: FormRequestOptions = {}

  /** Data extractor instance for getting raw data from context */
  private dataExtractor = new DataExtractor()

  /**
   * Authorization check (optional)
   *
   * Checks if the user has permission to perform this request before validating data.
   * This allows you to integrate authorization logic within the same class, following the "authorize first, then validate" best practice.
   *
   * @returns Returns `true` to allow validation to proceed; returns `false` to throw a 403 Forbidden error.
   *
   * @example
   * ```typescript
   * authorize(ctx: Context) {
   *   const user = ctx.get('user')
   *   // Only verified administrators can perform this operation
   *   return user?.role === 'admin'
   * }
   * ```
   */
  authorize?(ctx: Context): boolean | Promise<boolean>

  /**
   * Custom authorization failure message (optional)
   *
   * Provides a more specific error message when `authorize()` returns false.
   * Helps explain to the user why they are not authorized to perform the operation.
   *
   * @returns Custom authorization error message
   *
   * @example
   * ```typescript
   * authorizationMessage() {
   *   return 'Only administrators can create new users'
   * }
   * ```
   */
  authorizationMessage?(): string

  /**
   * Data transformation before validation (optional)
   *
   * Pre-processes the raw data before schema validation.
   * Suitable for type coercion, adding default values, or cleaning user input.
   *
   * @param data - Raw data extracted from the request
   * @returns Transformed data, which will be passed to the schema for validation
   *
   * @example
   * ```typescript
   * transform(data: any) {
   *   return {
   *     ...data,
   *     age: data.age ? parseInt(data.age) : undefined,  // Convert string to number
   *     createdAt: new Date()  // Add timestamp
   *   }
   * }
   * ```
   */
  transform?(data: unknown): unknown

  /**
   * Custom error message mapping (optional)
   *
   * Defines field-level custom error messages to override the schema validator's default messages.
   * Uses the `field_name.error_code` format as the key to provide more user-friendly and localized messages.
   *
   * @returns Error message mapping object, where keys are in `field.code` format and values are custom messages
   *
   * @example
   * ```typescript
   * messages() {
   *   return {
   *     'email.invalid_string': 'Please enter a valid email address',
   *     'name.too_small': 'Name must be at least 2 characters',
   *     'age': 'Age must be a valid number'  // Field name only also works
   *   }
   * }
   * ```
   */
  messages?(): Record<string, string>

  /**
   * Custom redirect URL on validation failure (optional)
   *
   * Used for traditional server-side rendered applications to redirect the user to a specified page when validation fails.
   * Typically not needed for SPA applications as errors are returned in JSON format.
   *
   * @returns The target URL for redirection
   *
   * @example
   * ```typescript
   * redirect() {
   *   return '/users/create'  // Return to create user form page on validation failure
   * }
   * ```
   */
  redirect?(): string

  /**
   * Extract raw data from the request context based on the data source
   *
   * This method extracts data from different parts of the request based on the `source` property setting:
   * - `json`: Parses the JSON request body
   * - `form`: Parses form data (FormData)
   * - `query`: Parses URL query parameters
   * - `param`: Parses route parameters
   *
   * @param ctx - Gravito request context object
   * @returns Raw data object, unvalidated
   *
   * @example
   * ```typescript
   * const request = new StoreUserRequest()
   * request.source = 'json'
   * const rawData = await request.getData(ctx)
   * // rawData might be { name: "John", email: "john@example.com" }
   * ```
   */
  public async getData(ctx: Context): Promise<unknown> {
    return this.dataExtractor.extract(ctx, this.source)
  }

  /**
   * Get localized error message for a field with performance caching.
   *
   * Resolution order:
   * 1. Custom messages from messages() method (cached)
   * 2. MessageProvider (if configured)
   * 3. Default validator message
   */
  private getMessage(field: string, code: string | undefined, defaultMessage: string): string {
    // Import MessageCache lazily to avoid circular dependency
    const { MessageCache } = require('./core/MessageCache')

    // Create cache key including instance reference via constructor name
    const instanceId = this.constructor.name
    const cacheKey = MessageCache.createCacheKey(instanceId, field, code, defaultMessage)

    // Use cached message resolution
    return MessageCache.getCachedMessage(cacheKey, () => {
      // 1. Check cached custom messages from messages() method
      if (this.messages) {
        const customMessages = MessageCache.getInstanceMessages(this)
        if (customMessages) {
          const key = code ? `${field}.${code}` : field
          if (customMessages[key]) {
            return customMessages[key]
          }
          // Try field-only key
          if (customMessages[field]) {
            return customMessages[field]
          }
        }
      }

      // 2. Check i18n message provider
      if (this.options.messageProvider) {
        return this.options.messageProvider.getMessage(code ?? '', field, defaultMessage)
      }

      // 3. Return default message
      return defaultMessage
    })
  }

  private getErrorMessage(field: string, code: string | undefined, message: string): string {
    return this.getMessage(field, code, message)
  }

  /**
   * Execute the full authorization and validation process
   *
   * This method is the core of FormRequest, executing in the following order:
   * 1. Check authorization (if `authorize` method is defined)
   * 2. Extract data from context
   * 3. Execute data transformation (if `transform` method is defined)
   * 4. Validate data using the schema
   * 5. Apply custom error messages (if `messages` method is defined)
   *
   * This method typically does not need to be called directly; it is automatically executed by the `validateRequest()` middleware.
   *
   * @param ctx - Gravito request context object
   * @returns Returns `{ success: true, data: validatedData }` on successful validation; returns an object with error details on failure.
   *
   * @example
   * ```typescript
   * const request = new StoreUserRequest()
   * const result = await request.validate(ctx)
   *
   * if (result.success) {
   *   console.log('Validation successful:', result.data)
   * } else {
   *   console.log('Validation failed:', result.error.error.details)
   * }
   * ```
   */
  async validate(
    ctx: Context
  ): Promise<
    { success: true; data: unknown } | { success: false; error: ValidationErrorResponse }
  > {
    const messageProvider = this.options.messageProvider ?? new DefaultMessageProvider()

    // 1. Authorization check
    if (this.authorize) {
      const authorized = await this.authorize(ctx)
      if (!authorized) {
        const authMessage =
          this.authorizationMessage?.() ?? messageProvider.getUnauthorizedMessage()
        return {
          success: false,
          error: {
            success: false,
            error: {
              code: 'AUTHORIZATION_ERROR',
              message: authMessage,
              details: [],
            },
          },
        }
      }
    }

    // 2. Get data
    let data = await this.getData(ctx)

    // 3. Transform if needed
    if (this.transform) {
      data = this.transform(data)
    }

    // 4. Validate with appropriate schema library
    const validator = SchemaValidatorFactory.getValidator(this.schema)
    const result = await validator.validate(this.schema, data)

    if (!result.success) {
      const details: ValidationErrorDetail[] = (result.errors ?? []).map((err) => ({
        field: err.path.join('.'),
        message: this.getErrorMessage(err.path.join('.'), err.code, err.message),
        code: err.code,
      }))

      return {
        success: false,
        error: {
          success: false,
          error: {
            code: 'VALIDATION_ERROR',
            message: messageProvider.getValidationFailedMessage(),
            details,
          },
        },
      }
    }

    return { success: true, data: result.data }
  }

  /**
   * Extract validation schema metadata for frontend use (Blueprint)
   *
   * Converts backend validation rules into a serializable JSON format, allowing the frontend to implement the same validation logic.
   * This avoids duplicate definitions of validation rules on both frontend and backend and ensures consistency of validation logic.
   *
   * Typical Uses:
   * - Display validation errors in real-time in frontend forms
   * - Generate dynamic form UI
   * - Provide API documentation
   *
   * @returns A metadata object containing the schema structure and validation rules
   *
   * @example
   * ```typescript
   * const request = new StoreUserRequest()
   * const blueprint = request.getBlueprint()
   * // Returns something like:
   * // {
   * //   fields: {
   * //     name: { type: 'string', required: true, minLength: 2 },
   * //     email: { type: 'string', required: true, format: 'email' }
   * //   },
   * //   source: 'json'
   * // }
   *
   * // The frontend can use this blueprint to validate user input
   * app.get('/api/users/blueprint', (ctx) => {
   *   const request = new StoreUserRequest()
   *   return ctx.json(request.getBlueprint())
   * })
   * ```
   */
  getBlueprint(): Record<string, any> {
    return BlueprintGenerator.generateBlueprint(this.schema, this.source)
  }
}

/**
 * Create a validation middleware
 *
 * Converts a FormRequest class into a Gravito middleware used to automatically validate requests before the route handler executes.
 * This is the primary way to use FormRequest, providing a clean API to integrate validation logic.
 *
 * Workflow:
 * 1. Create a singleton instance for each FormRequest class (performance optimization)
 * 2. Execute the FormRequest's `validate()` method
 * 3. If validation passes, store the validated data in `ctx.get('validated')`
 * 4. If validation fails, throw a `ValidationException` or `AuthorizationException`
 *
 * @param RequestClass - Constructor of the FormRequest class
 * @returns A Gravito middleware handler, which can be used directly in route definitions
 * @throws {ValidationException} When request data does not comply with schema rules
 * @throws {AuthorizationException} When the `authorize()` method returns false
 *
 * @example
 * ```typescript
 * import { validateRequest } from '@gravito/impulse'
 * import { StoreUserRequest } from './requests/StoreUserRequest'
 *
 * // Use validation middleware in a route
 * app.post('/users', validateRequest(StoreUserRequest), async (ctx) => {
 *   // Data is already validated at this point and can be used safely
 *   const data = ctx.get('validated') as z.infer<typeof StoreUserRequest.prototype.schema>
 *   const user = await db.users.create(data)
 *   return ctx.json(user, 201)
 * })
 *
 * // Multiple middlewares can also be composed
 * app.post('/admin/users',
 *   authenticate(),
 *   validateRequest(StoreUserRequest),
 *   async (ctx) => {
 *     // ...
 *   }
 * )
 * ```
 */
export function validateRequest<T>(RequestClass: new () => FormRequest<T>): MiddlewareHandler {
  return async (ctx, next) => {
    // Import FormRequestInstanceCache lazily to avoid circular dependency
    const { FormRequestInstanceCache } = require('./core/FormRequestInstanceCache')

    // Use cached instance instead of creating new one every time
    const request = FormRequestInstanceCache.getInstance(RequestClass)
    const result = await request.validate(ctx)

    if (!result.success) {
      const errorData = result.error.error

      if (errorData.code === 'AUTHORIZATION_ERROR') {
        throw new AuthorizationException(errorData.message)
      }

      if (errorData.code === 'VALIDATION_ERROR') {
        const exception = new ValidationException(
          errorData.details.map((d: any) => ({
            field: d.field,
            message: d.message,
            ...(d.code !== undefined ? { code: d.code } : {}),
          })),
          errorData.message
        )

        if (request.redirect) {
          const url = request.redirect()
          if (url) {
            exception.withRedirect(url)
          }
        }

        // Attach input data for flashing
        exception.withInput(await request.getData(ctx))

        throw exception
      }

      // Fallback for unknown errors (shouldn't happen with current implementation)
      const status: ContentfulStatusCode = request.options.errorStatus ?? 422
      return ctx.json(result.error, status)
    }

    // Store validated data in context
    ctx.set('validated', result.data)
    await next()
    return undefined
  }
}

// Module augmentation for GravitoVariables (new abstraction)
declare module '@gravito/core' {
  interface GravitoVariables {
    /** Validated request data from FormRequest */
    validated?: unknown
  }
}
